### ISSUE TITLE
Implement Custom "Not Found" Page and Handle Broken Links

### ISSUE THREAD

**Issue by Md-Dipu** [Md-Dipu/learning-parcel-and-workflow#13]
We need to create a custom "404 - Not Found" page to handle broken or invalid links gracefully. This page should be user-friendly, visually appealing, and provide users with helpful options (such as back-to-home). 

#### **Tasks**
- [ ] **Design and Create 404 Page**  
  Design a custom "404 - Not Found" page that is visually consistent with the rest of the site. Include a message informing users that the page they are looking for doesn’t exist.
  
- [ ] **Navigation and Call-to-Action (CTA)**  
  Add clear navigation options or CTAs such as links to the homepage, a search bar, or popular pages to help users find their way.
  
- [ ] **Handle Broken Links**  
  Identify potential broken links within the site and replace them with not found page link. 

#### **Acceptance Criteria**
- The custom "404 - Not Found" page is visually consistent with the site design and offers clear navigation options.
- Broken links within the website are replaced with `not found` page.

**Comment by Mahedi-432A** [comment]
i can easily make and design 404 page but handling broken page is harder for me. i need some hints about this.

**Comment by Md-Dipu** [comment]
I mean replace broken links with link of 404 page.
